<?php

return [

    'accepted' => 'Polje :attribute mora biti sprejeto.',
    'accepted_if' => 'Polje :attribute mora biti sprejeto, ko je :other :value.',
    'active_url' => 'Polje :attribute mora biti veljaven URL.',
    'after' => 'Polje :attribute mora biti datum po :date.',
    'after_or_equal' => 'Polje :attribute mora biti datum po ali enak :date.',
    'alpha' => 'Polje :attribute lahko vsebuje samo črke.',
    'alpha_dash' => 'Polje :attribute lahko vsebuje samo črke, številke, pomišljaje in podčrtaje.',
    'alpha_num' => 'Polje :attribute lahko vsebuje samo črke in številke.',
    'array' => 'Polje :attribute mora biti matrika (array).',
    'ascii' => 'Polje :attribute lahko vsebuje samo enobajtne alfanumerične znake in simbole.',
    'before' => 'Polje :attribute mora biti datum pred :date.',
    'before_or_equal' => 'Polje :attribute mora biti datum pred ali enak :date.',
    'between' => [
        'array' => 'Polje :attribute mora imeti med :min in :max elementov.',
        'file' => 'Polje :attribute mora biti med :min in :max kilobajti.',
        'numeric' => 'Polje :attribute mora biti med :min in :max.',
        'string' => 'Polje :attribute mora biti med :min in :max znaki.',
    ],
    'boolean' => 'Polje :attribute mora biti resnično ali neresnično.',
    'can' => 'Polje :attribute vsebuje nedovoljeno vrednost.',
    'confirmed' => 'Potrditev polja :attribute se ne ujema.',
    'current_password' => 'Geslo je napačno.',
    'date' => 'Polje :attribute mora biti veljaven datum.',
    'date_equals' => 'Polje :attribute mora biti datum enak :date.',
    'date_format' => 'Polje :attribute se mora ujemati s formatom :format.',
    'decimal' => 'Polje :attribute mora imeti :decimal decimalnih mest.',
    'declined' => 'Polje :attribute mora biti zavrnjeno.',
    'declined_if' => 'Polje :attribute mora biti zavrnjeno, ko je :other :value.',
    'different' => 'Polje :attribute in :other morata biti različna.',
    'digits' => 'Vrednost polja :attribute mora biti število.',
    'digits_between' => 'Polje :attribute mora vsebovati med :min in :max števil.',
    'dimensions' => 'Polje :attribute ima neveljavne dimenzije slike.',
    'distinct' => 'Polje :attribute ima podvojeno vrednost.',
    'doesnt_end_with' => 'Polje :attribute se ne sme končati z eno od naslednjih: :values.',
    'doesnt_start_with' => 'Polje :attribute se mora začeti z eno izmed naslednjih vrednosti.',
    'email' => 'Polje :attribute mora biti veljaven e-poštni naslov.',
    'ends_with' => 'Polje :attribute se mora končati z eno od naslednjih: :values.',
    'enum' => 'Izbrani :attribute je neveljaven.',
    'exists' => 'Izbrani :attribute je neveljaven.',
    'extensions' => 'Polje :attribute mora imeti eno od naslednjih razširitev: :values.',
    'file' => 'Polje :attribute mora biti datoteka.',
    'filled' => 'Polje :attribute mora vsebovati vrednost.',
    'gt' => [
        'array' => 'Polje :attribute mora vsebovati več kot : elementov.',
        'file' => 'Polje :attribute mora vsebovati več kot :kilobajtov.',
        'numeric' => 'Polje :attribute mora biti večje od :value.',
        'string' => 'Polje :attribute mora vsebovati več kot znakov.',
    ],
    'gte' => [
        'array' => 'Polje :attribute mora vsebovati :value ali več znakov.',
        'file' => 'Polje :attribute mora vsebovati :value ali več kilobajtov.',
        'numeric' => 'Polje :attribute mora biti večje ali enako :value.',
        'string' => 'Polje :attribute mora vsebovati :value ali več znakov.',
    ],
    'hex_color' => 'Polje :attribute mora biti veljavna heksadecimalna barva.',
    'image' => 'Polje :attribute mora biti slika.',
    'in' => 'Izbrani :attribute je neveljaven.',
    'in_array' => 'Polje :attribute mora obstajati v :other.',
    'integer' => 'Polje :attribute mora biti celo število.',
    'ip' => 'Polje :attribute mora biti veljaven IP naslov.',
    'ipv4' => 'Polje :attribute mora biti veljaven IPv4 naslov.',
    'ipv6' => 'Polje :attribute mora biti veljaven IPv6 naslov.',
    'json' => 'Polje :attribute mora biti niz črk.',
    'lowercase' => 'Polje :attribute mora biti z malimi črkami.',
    'lt' => [
        'array' => 'Polje :attribut mora vsebovati manj kot :value elementov.',
        'file' => 'Polje :attribut mora vsebovati manj kot :value kilobajtov.',
        'numeric' => 'Polje :attribute mora vsebovati manj kot :value znakov.',
        'string' => 'Polje :attribute mora vsebovati manj kot ali enako :value znakov.',
    ],
    'lte' => [
        'array' => 'Polje :attribute ne sme vsebovati več kot :value elementov.',
        'file' => 'Polje :attribute mora vsebovati manj ali enako kot :value kilobajtov.',
        'numeric' => 'Polje :attribute mora biti manjše ali enako :value.',
        'string' => 'Polje :attribute mora vsebovati manj ali enako kot :value znakov.',
    ],
    'mac_address' => 'Polje :attribute mora biti veljaven MAC naslov.',
    'max' => [
        'array' => 'Polje :attribute ne sme vsebovati več kot :max elementov.',
        'file' => 'Polje :attribute ne sme vsebovati več kot :max kilobajtov.',
        'numeric' => 'Polje :attribute ne sme biti večje od :max.',
        'string' => 'Polje :attribuite ne vsebovati več kot :max znakov.',
    ],
    'max_digits' => 'Polje :attribute ne sme vsebovati več kot :max številk.',
    'mimes' => 'Polje :attribute mora biti datoteka tipa: :values.',
    'mimetypes' => 'Polje :attribute mora biti datoteka tipa: :values.',
    'min' => [
        'array' => 'Polje :attribute mora vsebovati najmanj :min elementov.',
        'file' => 'Polje :attribute mora vsebovati najmanj :min kilobajtov.',
        'numeric' => 'Polje :attribute mora biti vsaj :min.',
        'string' => 'Polje :attribute mora vsebovati :min znakov.',
    ],
    'min_digits' => 'Polje :attribute mora vsebovati najmanj :min števil.',
    'missing' => 'Polje :attribute mora manjkati.',
    'missing_if' => 'Polje :attribute mora biti prazno, kadar je :other enako kot :value.',
    'missing_unless' => 'Polje :attribute mora biti prazno, razen če je :other enako kot :value.',
    'missing_with' => 'Polje :attribute mora biti prazno, kadar je vrednost :others prikazana.',
    'missing_with_all' => 'Polje a:attribute mora biti prazno, kadar so vrednosti :values prikazane.',
    'multiple_of' => 'Polje :attribute mora biti večkratnik :value.',
    'not_in' => 'Izbrani :attribute je neveljaven.',
    'not_regex' => 'Format :attribute je neveljaven.',
    'numeric' => 'Polje :attribute mora biti številka.',
    'password' => [
        'letters' => 'Polje :attribute mora vsebovati najmanj eno črko.',
        'mixed' => 'Polje :attribute vsebovati eno veliko in eno malo črko.',
        'numbers' => 'Polje :attribute mora vsebovati najmanj eno število.',
        'symbols' => 'Polje :attribute mora vsebovati vsebovati najmanj en simbol.',
        'uncompromised' => 'Podano polje :attribute se je pojavilo v podatkovnem vdoru. Prosimo, izberite drugo :attribute.',
    ],
    'present' => 'Polje :attribute mora biti ovrednoteno.',
    'present_if' => 'Polje :attribute mora biti ovrednoteno, kadar je :other enako kot :value.',
    'present_unless' => 'Polje :attribute mora biti ovrednoteno, razen če je :other enako kot :vrednost.',
    'present_with' => 'Polje :attribute mora biti ovrednoteno, kadar so podane vrednosti :values.',
    'present_with_all' => 'Polje :attribute mora biti prisotno, ko so :values prisotni.',
    'prohibited' => 'Polje :attribute je prepovedano.',
    'prohibited_if' => 'Polje :attribute je prepovedano, ko je :other :value.',
    'prohibited_unless' => 'Polje attribute: je prepovedano razen, če :others ustreza vrednostim :values.',
    'prohibits' => 'Polje :attribute zavrne prikaz :other.',
    'regex' => 'Format :attribute je neveljaven.',
    'required' => 'Polje :attribute je zahtevano.',
    'required_array_keys' => 'Polje :attribute mora omogačati vnos vrednosti :values.',
    'required_if' => 'Polje :attribute je zahtevano. kadar je :other enako kot :value.',
    'required_if_accepted' => 'Polje :attribute je zahtevano, kadar je :other odobren.',
    'required_unless' => 'Polje :attribute je zahtevano, razen če je :others v opsegu vrednosti :values.',
    'required_with' => 'Polje :attribute je zahtevano, kadar je vrednost :values podana.',
    'required_with_all' => 'Polje :attribute je zahtevano, kadar so vrednosti :values podane.',
    'required_without' => 'Polje :attribute je zahteveno, kadar vrednost :values ni podana.',
    'required_without_all' => 'Polje :attribute je zahtevano, kadar nobena od vrednosti ni podana.',
    'same' => 'Polje :attribute se mora ujemati s/z :other.',
    'size' => [
        'array' => 'Polje :attribute mora vsebovati :size elemente.',
        'file' => 'Polje :attribute mora biti velikosti :size kilobajtov.',
        'numeric' => 'Polje :attribute mora biti velikosti :size.',
        'string' => 'Polje :attribute mora vsebovati :size elementav.',
    ],
    'starts_with' => 'Polje :attribute se mora začeti z enim od naslednjih: :values.',
    'string' => 'Polje :attribute mora biti niz.',
    'timezone' => 'Polje :attribute mora biti veljaven časovni pas.',
    'unique' => 'Polje :attribute je že zasedeno.',
    'uploaded' => 'Nalaganje polja :attribute ni uspelo.',
    'uppercase' => ':attribute mora biti izpisan z velikimi tiskanimi črkami.',
    'url' => 'Polje :attribute mora biti veljaven URL.',
    'ulid' => 'Polje :attribute mora biti veljaven ULID.',
    'uuid' => 'Polje :attribute mora biti veljaven UUID.',
    'custom' => [
        'avatar' => [
            'base64image' => ':attribute mora biti v veljavnem formatu (jpeg, png, jpg, gif, svg).',
        ],
        'atLeastOneRole' => [
            'required' => 'Izbrati morate vsaj eno možnost.',
        ],
    ],

];
