<?php

return [

    'accepted' => 'To :attribute pole  musi zostać zaakceptowane',
    'accepted_if' => 'To :attribute pole musi zostać zaakceptowane gdy :other jest :value.',
    'active_url' => 'To :attribute pole musi być prawidłowym adresem URL',
    'after' => 'To :attribute pole musi być data po :date.',
    'after_or_equal' => 'To :attribute pole musi być data po lub równa :date.',
    'alpha' => 'To :attribute pole musi zawierać tylko litery.',
    'alpha_dash' => 'To :attribute pole musi zawierać tylko litery, cyfry, myślniki i podkreślenia',
    'alpha_num' => 'To :attribute pole musi zawierać tylko litery i cyfry.',
    'array' => 'To :attribute pole musi być tablicą.',
    'ascii' => 'To :attribute pole musi zawierać tylko jednobajtowe znaki alfanumeryczne i symbole.',
    'before' => 'To :attribute pole musi być data przed :date.',
    'before_or_equal' => 'To :attribute pole musi być data po lub równa :date.',
    'between' => [
        'array' => 'To :attribute pole musi być pomiędzy :min and :max  pozycje.',
        'file' => 'To :attribute pole musi być pomiędzy :min and :max kilobajty.',
        'numeric' => 'To :attribute pole musi być pomiędzy :min and :max.',
        'string' => 'To :attribute pole musi być pomiędzy :min and :max znaki.',
    ],
    'boolean' => 'To :attribute pole musi być prawda lub fałsz.',
    'can' => 'To :attribute pole zawiera nieautoryzowaną wartość.',
    'confirmed' => 'To potwierdzenie :attribute pole nie pasuje.',
    'current_password' => 'Nieprawidłowe hasło.',
    'date' => 'To :attribute pole musi być ważną datą.',
    'date_equals' => 'To :attribute pole musi być data po lub równa :date.',
    'date_format' => 'To :attribute pole musi pasować do formatu :format.',
    'decimal' => 'To :attribute pole musi zawierać :decimal decimal places.',
    'declined' => 'To :attribute pole musi zostać odrzucone.',
    'declined_if' => 'To :attribute pole musi zostać odrzucone gdy :other is :value.',
    'different' => 'To :attribute pole i :other musi być inne.',
    'digits' => 'To :attribute pole musi być :digits digits.',
    'digits_between' => 'To :attribute pole musi być pomiędzy :min and :max  cyfry.',
    'dimensions' => 'To :attribute pole ma nieprawidłowe wymiary obrazu.',
    'distinct' => 'To :attribute pole ma zduplikowaną wartość.',
    'doesnt_end_with' => 'To :attribute pole nie może kończyć się jedną z następujących: :values.',
    'doesnt_start_with' => 'To :attribute pole nie może zaczynać się jedną z następujących: :values.',
    'email' => 'To :attribute pole musi być prawidłowy adres e-mail.',
    'ends_with' => 'To :attribute pole musi kończyć się jedną z następujących: :values.',
    'enum' => 'Wybrany :attribute jest nieprawidłowy.',
    'exists' => 'Wybrany :attribute jest nieprawidłowy.',
    'extensions' => 'To :attribute pole musi mieć jedno z następujących rozszerzeń: :values.',
    'file' => 'To :attribute pole musi być plikiem.',
    'filled' => 'To :attribute pole musi być wartością.',
    'gt' => [
        'array' => 'To :attribute pole musi mieć więcej niż :value pozycji.',
        'file' => 'To :attribute pole musi być większe niż :value kilobajty.',
        'numeric' => 'To :attribute pole musi być większe niż :value.',
        'string' => 'To :attribute pole musi być większa niż :value znaki.',
    ],
    'gte' => [
        'array' => 'Pole :atrybut musi zawierać elementy o wartości :lub więcej.',
        'file' => 'To :attribute pole musi być większe lub równe :value kilobajty.',
        'numeric' => 'To :attribute pole musi być większe lub równe :value.',
        'string' => 'To: pole atrybutu musi być większe lub równe: wartość znaków.',
    ],
    'hex_color' => 'To :attribute pole musi być prawidłowym kolorem szesnastkowym.',
    'image' => 'Pole :attribute musi być obrazkiem.',
    'in' => 'Wybrany :atrybut jest nieprawidłowy.',
    'in_array' => 'To :attribute pole  musi istnieć w :other.',
    'integer' => 'To :attribute pole musi być liczbą całkowitą.',
    'ip' => 'To :attribute pole musi być prawidłowym adresem IP.',
    'ipv4' => 'To :attribute pole musi być prawidłowym adresem IPv4.',
    'ipv6' => 'To :attribute pole musi być prawidłowym adresem IPv4.',
    'json' => 'To :attribute pole musi być prawidłowym ciągiem JSON.',
    'lowercase' => 'To :attribute pole musi być małymi literami.',
    'lt' => [
        'array' => 'To :attribute pole musi być mniej niż :value pozycji.',
        'file' => 'To :attribute pole musi być mniej niż :value kilobajty.',
        'numeric' => 'To :attribute pole musi być mniej niż :value.',
        'string' => 'To :attribute pole musi być mniej niż :value znaki.',
    ],
    'lte' => [
        'array' => 'To :attribute pole  nie może mieć więcej niż :value pozycji.',
        'file' => 'To :attribute pole musi być mniej lub równa niż :value kilobajty.',
        'numeric' => 'To :attribute pole musi  być mniejsze niż czy równe :value.',
        'string' => 'To :attribute pole musi być mniejsze niż czy równe :value znaki.',
    ],
    'mac_address' => 'To :attribute pole musi być prawidłowym adresem MAC.',
    'max' => [
        'array' => 'To :attribute pole nie może mieć więcej niż :value pozycji.',
        'file' => 'To :pole atrybutu nie może być większe niż :max kilobajty.',
        'numeric' => 'To :attribute pole nie może być większe niż :max.',
        'string' => 'To :attribute pole nie może być większe niż :max znaki.',
    ],
    'max_digits' => 'To :attribute pole nie może być większe niż :max cyfry.',
    'mimes' => 'To :attribute pole musi być plikiem typu: :values.',
    'mimetypes' => 'To :attribute pole musi być plikiem typu: :values.',
    'min' => [
        'array' => 'To :attribute pole musi mieć co najmniej :min pozycji.',
        'file' => 'To :attribute pole musi być co najmniej :min kilobajty.',
        'numeric' => 'To :attribute pole musi być co najmniej :min.',
        'string' => 'To :attribute pole musi być co najmniej :min znaki.',
    ],
    'min_digits' => 'To :attribute pole musi być co najmniej :min cyfry.',
    'missing' => 'To :attribute pole musi być brakujące.',
    'missing_if' => 'To :attribute pole musi być brakujące, gdy :other is  :value.',
    'missing_unless' => 'To :attribute pole musi być brakujące, chyba, że :other is  :value.',
    'missing_with' => 'To :attribute pole musi być brakujące, gdy :valuesi są obecne.',
    'missing_with_all' => 'To :attribute pole musi być brakujące, gdy :values są obecne.',
    'multiple_of' => 'To :attribute pole musi być wielokrotnością :value.',
    'not_in' => 'Wybrany :attribute jest nieprawidłowy.',
    'not_regex' => 'To :attribute pole format jest nieprawidłowy.',
    'numeric' => 'To :attribute pole musi być numerem.',
    'password' => [
        'letters' => 'To :attribute pole musi zawierać co najmniej jedną literę',
        'mixed' => 'To :attribute pole musi zawierać co najmniej jedną wielka i jedną małą literę.',
        'numbers' => 'To :attribute pole musi zawierać co najmniej jedną cyfrę.',
        'symbols' => 'To :attribute pole musi zawierać co najmniej jeden symbol.',
        'uncompromised' => 'Dany :attribute pojawił się w wycieku danych. Proszę wybrać inny :attribute.',
    ],
    'present' => 'To :attribute pole musi być obecne.',
    'present_if' => 'To :attribute pole musi być obecne, gdy :other is :value.',
    'present_unless' => 'To :attribute pole musi być obecne, chyba że :other is :value.',
    'present_with' => 'To :attribute pole musi być obecne, gdy :values jest obecne.',
    'present_with_all' => 'To :attribute pole musi być obecne, gdy :values są obecne.',
    'prohibited' => 'To :attribute pole jest zabronione.',
    'prohibited_if' => 'Pole :attribute jest zabronione, gdy :other jest :value.',
    'prohibited_unless' => 'To :attribute pole  jest zabronione, chyba że ::other is in :values.',
    'prohibits' => 'To :attribute pole jest zabronione :other od bycia obecnym.',
    'regex' => 'To :attribute pole atrybutu jest nieważny.',
    'required' => 'To :attribute pole jest wymagane.',
    'required_array_keys' => 'To :attribute pole musi zawierać wpisy dla: :values.',
    'required_if' => 'To :attribute pole jest wymagane, gdy :other is :value.',
    'required_if_accepted' => 'To :attribute pole jest wymagane, gdy :other jest akceptowane.',
    'required_unless' => 'To :attribute pole jest wymagane, chyba, że :other is in :value.',
    'required_with' => 'To :attribute pole jest wymagane, gdy :values obecne.',
    'required_with_all' => 'To :attribute pole jest wymagane, gdy :values obecne.',
    'required_without' => 'To :attribute pole jest wymagane, gdy :values nie są obecne.',
    'required_without_all' => 'To :attribute pole jest wymagane, gdy :valuesi nie są obecne.',
    'same' => 'To :attribute pole musi odpowiadać :other',
    'size' => [
        'array' => 'To :attribute pole musi zawierać :size pozycji.',
        'file' => 'To :attribute pole musi być :size kilobajty.',
        'numeric' => 'To :attribute pole musi być :size.',
        'string' => 'To :attribute pole musi być :size znaki.',
    ],
    'starts_with' => 'To :attribute pole musi zaczynać się od jednej z następujących :values. ',
    'string' => 'To :attribute pole musi być ciągiem znaków.',
    'timezone' => 'To :attribute pole musi być prawidłową strefą czasową.',
    'unique' => 'Ten :attribute został już wzięty.',
    'uploaded' => 'Ten :attribute nie udało się przesłać.',
    'uppercase' => 'To :attribute pole musi być  pisane wielkimi literami.',
    'url' => 'To :attribute pole musi być prawidłowym adresem URL.',
    'ulid' => 'To :attribute pole musi być ważnym ULID.',
    'uuid' => 'Pole :attribute musi być prawidłowym identyfikatorem UUID.',
    'custom' => [
        'avatar' => [
            'base64image' => 'Plik musi być ważnym obrazkiem (JPEG, PNG, JPG, GIF, SVG).',
        ],
        'atLeastOneRole' => [
            'required' => 'Musisz wybrać co najmniej jedną opcję.',
        ],
    ],

];
